version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp-build-prerequisites:0.3.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - checkout:
          path: /projects/ishiko/cpp/png
      - run:
          name: Build
          command: cd /projects/ishiko/cpp/png/build/gnumake && make
      - run:
          name: Test build
          command: cd /projects/ishiko/cpp/png/tests/build/gnumake && make
      - run:
          name: Run the tests
          command: cd /projects/ishiko/cpp/png/tests/build/gnumake && ./IshikoPNGTests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/IshikoPNG.xml
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/IshikoPNG.xml
          destination: IshikoErrors-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/IshikoPNG.xml
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
